apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- stateful-set.yaml
images:
- name: grc.azk8s.cn/$(project)/application-controller
  newName: grc.azk8s.cn/$(project)/application-controller
  newTag: latest
