apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
- name: grc.azk8s.cn/kubeflow-images-public/pytorch-operator
  newName: grc.azk8s.cn/kubeflow-images-public/pytorch-operator
  newTag: v1.0.0-g047cf0f
