apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-scheduledworkflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-scheduledworkflow
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: gcr.azk8s.cn/ml-pipeline/scheduledworkflow
          imagePullPolicy: IfNotPresent
      serviceAccountName: ml-pipeline-scheduledworkflow
