apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistenceagent
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: grc.azk8s.cn/ml-pipeline/persistenceagent
        imagePullPolicy: IfNotPresent
      serviceAccountName: ml-pipeline-persistenceagent
