apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline
resources:
  - config-map.yaml
  - deployment.yaml
  - role-binding.yaml
  - role.yaml
  - service-account.yaml
  - service.yaml
images:
  - name: gcr.azk8s.cn/ml-pipeline/api-server
    newTag: 0.1.31
    newName: gcr.azk8s.cn/ml-pipeline/api-server
