apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameprefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-visualizationserver
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: gcr.azk8s.cn/ml-pipeline/visualization-server
    newTag: 0.1.27
    newName: gcr.azk8s.cn/ml-pipeline/visualization-server
