apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- job.yaml
- certificate.yaml
namespace: kubeflow
commonLabels:
  kustomize.component: basic-auth-ingress
images:
- name: grc.azk8s.cn/kubeflow-images-public/ingress-setup
  newName: grc.azk8s.cn/kubeflow-images-public/ingress-setup
  newTag: latest
